#!/bin/bash
#SBATCH --job-name=graph_generation
#SBATCH --time=04:00:00
#SBATCH --ntasks=576
#SBATCH --cpus-per-task=1
#SBATCH --output=../../outputs/gen_out
#SBATCH --error=../../outputs/gen_error
#SBATCH --partition=short
##SBATCH --partition=byteboost

module purge
PROC=576
cd /lustre/home/amos/scratch/keegan_byteboost_25/parallel_bridge-artic_algos  
cd ookami
source modules.sh
which srun
cd ..
make -B generate
mpirun -np $PROC ./generate 2147483648 16 
mpirun -np $PROC generate 2147483648 8
mpirun -np $PROC generate 2147483648 4
mpirun -np $PROC generate 2147483648 2
mpirun -np $PROC generate 2147483648 32
