#!/bin/bash
#SBATCH --job-name=bridges_and_articulation_points
#SBATCH --time=02:00:00
#SBATCH --ntasks=192
#SBATCH --cpus-per-task=1
#SBATCH --mem=371G
#SBATCH --output=../outputs/out
#SBATCH --partition=staff
cd /scratch/user/u.ks124812/graph_parallel
source modules.sh
make -B test
