#!/bin/bash
#SBATCH --job-name=graph_generation
#SBATCH --time=1-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=192
#SBATCH --nodes=1
#SBATCH --mem=370G
#SBATCH --output=gen_out
#SBATCH --error=gen_error
#SBATCH --partition=staff

module purge
module load WebProxy 

cd /scratch/user/u.ks124812/parallel_bridge-artic_algos
source modules.sh
make -B generate
./generate 2000000000 8
