#!/bin/bash
#SBATCH --job-name=BRIDGE_STRONG_SCALING
#SBATCH --time=08:00:00
#SBATCH --ntasks=384
#SBATCH --nodes=4
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G
#SBATCH --exclusive
#SBATCH --output=../outputs/aces_custom_out
#SBATCH --error=../outputs/aces_custom_error
#SBATCH --gres=gpu:pvc:2
#SBATCH --partition=pvc
cd $SCRATCH/parallel_bridge-artic_algos
source modules.sh
make -B parallel
MAX_PROCESSES=384
echo "Starting cross node benchmarks"
BASE_VERT=268435456
for ((np=384; np<=MAX_PROCESSES; np*=2)); do
  file_name="./graphs/${BASE_VERT}_4.csv"
  mpirun -np $np parallel_runner $file_name 1
done
