#!/bin/bash
#SBATCH --job-name=graph_generation
#SBATCH --time=1-00:00:00
#SBATCH --ntasks=768
#SBATCH --cpus-per-task=1
#SBATCH --output=../outputs/gen_out
#SBATCH --error=../outputs/gen_error
#SBATCH --partition=cpu

module purge
module load WebProxy 
PROC=768
cd /scratch/user/u.ks124812/parallel_bridge-artic_algos
source modules.sh
make -B generate
mpirun -np $PROC generate 2147483648 16 
