#!/bin/bash
#SBATCH --job-name=BRIDGE_STRONG_SCALING
#SBATCH --time=08:00:00
#SBATCH --ntasks=96
#SBATCH --cpus-per-task=1
#SBATCH --mem=488G
#SBATCH --exclusive
#SBATCH --output=../outputs/strong_scaling_output
#SBATCH --error=../outputs/strong_scaling_error
#SBATCH --gres=gpu:pvc:2
#SBATCH --partition=pvc
cd $SCRATCH/parallel_bridge-artic_algos
source modules.sh
make -B parallel
MAX_PROCESSES=96
echo "Starting cross node benchmarks"
BASE_VERT=75497472
for ((np=96; np<=MAX_PROCESSES; np+=192)); do
  file_name="./graphs/${BASE_VERT}_32.csv"
  mpirun -np $np parallel_runner $file_name 1
done
